// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.501
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import (
	"personal-website/internal"
	"personal-website/internal/components"
)

var (
	exampleOperations = []string{
		"2+2",
		"23.5 +((5 /2))",
		"2 * ((5/2+2) - (-3*1.5))",
		"-(2!)(-(3!))",
		"5^2",
		"25^0.5",
	}
)

func CalculatorProject() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = components.Head("projects.calculator.title").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<link rel=\"stylesheet\" href=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(internal.GetPathWithQueryHash("/assets/css/calculator.css")))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\"><script src=\"/assets/js/htmx.min.js\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var2 := ``
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var2)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</script><body theme=\"default\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.Header("projects.calculator.header-title").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<p>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(internal.Localize(ctx, "projects.calculator.intro"))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/pages/calculator.templ`, Line: 25, Col: 65}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</p><div class=\"operation-container\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ.RenderScriptItems(ctx, templ_7745c5c3_Buffer, handleTextAreaSize())
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<textarea id=\"operation\" type=\"text\" placeholder=\"Operation\" oninput=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 templ.ComponentScript = handleTextAreaSize()
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var4.Call)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\" name=\"operation\" hx-post=\"/calculator/operation\" hx-target=\".operation-result\"></textarea><div class=\"operation-result\"><p hx-swap-oob=\"true\" id=\"operation-equals\"></p><p hx-swap-oob=\"true\" id=\"result\"></p></div></div><div class=\"operation-example-container\"><p>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var5 string
		templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(internal.Localize(ctx, "projects.calculator.examples"))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/pages/calculator.templ`, Line: 45, Col: 72}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</p>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		for _, exampleOperation := range exampleOperations {
			templ_7745c5c3_Err = templ.RenderScriptItems(ctx, templ_7745c5c3_Buffer, setOperation(exampleOperation))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<p class=\"operation-example\" onclick=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var6 templ.ComponentScript = setOperation(exampleOperation)
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var6.Call)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var7 string
			templ_7745c5c3_Var7, templ_7745c5c3_Err = templ.JoinStringErrs(exampleOperation)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/pages/calculator.templ`, Line: 48, Col: 38}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var7))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div></body>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}

func setOperation(operation string) templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_setOperation_a0c6`,
		Function: `function __templ_setOperation_a0c6(operation){let operationElem = document.getElementById('operation')
    operationElem.value = operation
    operationElem.dispatchEvent(new Event('change'))}`,
		Call:       templ.SafeScript(`__templ_setOperation_a0c6`, operation),
		CallInline: templ.SafeScriptInline(`__templ_setOperation_a0c6`, operation),
	}
}

func handleTextAreaSize() templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_handleTextAreaSize_1e0f`,
		Function: `function __templ_handleTextAreaSize_1e0f(){let operationElem = document.getElementById('operation')
    operationElem.style.height = ""
    operationElem.style.height = operationElem.scrollHeight + "px"
    if (operationElem.style.originalWidth === undefined) {
        operationElem.style.originalWidth = operationElem.getBoundingClientRect().width
    }

    const fontWeight = window.getComputedStyle(operationElem, null).getPropertyValue('font-weight') || 'normal';
    const fontSize = window.getComputedStyle(operationElem, null).getPropertyValue('font-size') || '16px';
    const fontFamily = window.getComputedStyle(operationElem, null).getPropertyValue('font-family') || 'Times New Roman';

    let font = ` + "`" + `${fontWeight} ${fontSize} ${fontFamily}` + "`" + `;

    const canvas = document.createElement("canvas");
    const context = canvas.getContext("2d");
    context.font = font;
    const metrics = context.measureText(operationElem.value + "    "); // needs padding to work properly

    if (metrics.width > operationElem.style.originalWidth) {
        operationElem.style.width = 'clamp(' + operationElem.style.originalWidth + 'px, ' + metrics.width + 'px, 80%)'
    } else if (operationElem.value == "") {
        operationElem.style.width = 'fit-content'
    }}`,
		Call:       templ.SafeScript(`__templ_handleTextAreaSize_1e0f`),
		CallInline: templ.SafeScriptInline(`__templ_handleTextAreaSize_1e0f`),
	}
}
